# puerto de tu API local
server.port=8080

# URL de conexión al pooler
spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require

# usuario con el ID del proyecto
spring.datasource.username=postgres.lwwhfecpmieiqqnuhlkn

# contraseña
spring.datasource.password=Grupodessarrollo
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true